### ISSUE TITLE
Cuda driver reports: too many resources requested for launch

### ISSUE THREAD

**Issue by kevinstephano** [csarofeen/pytorch#1326]
## 🐛 Bug

Error message:
```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: CUDA driver error: too many resources requested for launch
```

Repro Code:

```
def f(add_1, primals_6, primals_7, getitem_1, getitem_2, add_5, _reshape_alias_14):
    native_layer_norm_backward_2 = torch.ops.aten.native_layer_norm_backward(_reshape_alias_14, add_1, [1280], getitem_1, getitem_2, primals_6, primals_7, [True, True, True]);  _reshape_alias_14 = add_1 = getitem_1 = getitem_2 = primals_6 = primals_7 = None
    getitem_15 = native_layer_norm_backward_2[0];  native_layer_norm_backward_2 = None
    add_8 = torch.ops.aten.add(add_5, getitem_15);  add_5 = getitem_15 = None
    sum_6 = torch.ops.aten.sum(add_8, [0], True);  add_8 = None
    return (sum_6,)
inp = [(torch.Size([40, 197, 1280]), torch.float16), (torch.Size([1280]), torch.float16), (torch.Size([1280]), torch.float16), (torch.Size([40, 197, 1]), torch.float32), (torch.Size([40, 197, 1]), torch.float32), (torch.Size([40, 197, 1280]), torch.float16), (torch.Size([40, 197, 1280]), torch.float16)]
inp = [torch.randn(i, device='cuda', dtype=dtype) for (i, dtype) in inp]
f = torch.jit.script(f)
with torch.jit.fuser("fuser2"):
  for _ in range(5):
    f(*inp)
```

**Comment by csarofeen** [comment]
confirmed with @chillee that https://github.com/csarofeen/pytorch/pull/1296/files was not upstream and in his repository, should be fixed with that commit. Will wait until we push upstream to confirm and close.

**Comment by Chillee** [comment]
This issue is occurring again (I think it might have been fixed at some point in the past, but the repro in the issue still errors).

I've confirmed that @csarofeen's PR is upstream and in my local commit.

**Comment by Chillee** [comment]
This error is still present (with this repro) for me. I've checked that @csarofeen's PR is in my build.

**Comment by jjsjann123** [comment]
You are likely using CUDA11.1? Similar issue here: https://github.com/pytorch/pytorch/issues/75708#issuecomment-1105252534
Please let us know your cuda toolkit version if it's something else.

**Comment by Chillee** [comment]
That’s correct - we use the same cluster, and they’ve taken quite some time to upgrade the cuda toolkit :(

**Comment by jjsjann123** [comment]
Just for the record, this should be patched in #76226

**Comment by naoyam** [comment]
Closing as it seems to have been fixed
